### PR TITLE
Add a weather station app with explanation.

### PR DESCRIPTION
**Pull request by htotoo**
# What's new

- Added a weather station app, that shows only a message to look for the WS signals in the main SubGhz app.

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by htotoo** [comment]
Screenshot-20231007-200915

**Comment by Willy-JL** [comment]
not 100% on this... like i get the point but keeping this around im not sure is the correct way.

its gonna be mentioned in the changelog anyway, and stumbling around you can see the "ignore weather" option in subghz, and even then can just ask

**Comment by htotoo** [comment]
You're right. I made this, becaouse on Discord I saw someone installed back the weather app from labs.flipper, but it didn't worked (changes in a lib/subghz) may broke it, and flipper crashed. So with this method "noone" would install the app, and run into a crash. But I see the point of skipping this; just an idea.

**Comment by Willy-JL** [comment]
yeah others also think this is not the best solution, thanks anyway tho!

we will try to find out why the apps for weather station and pocsag from catalog crash however

**Pull request closed without merging**
