### PR TITLE
Added mykey 

### PR DESCRIPTION
**Pull request by grugnoymeme**
# What's new

- added mykey for coges

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by RogueMaster** [comment]
Is this your work? I also see it here: https://github.com/haisenteck/flipperzero-Haisenteck/

**Comment by Sil333033** [comment]
@grugnoymeme thanks for your contribution. Can you give a bit more info on this NFC decoder? Where is this type used? 

@RogueMaster wassup clowni. Can you fix nested for the community?

**Comment by grugnoymeme** [comment]
Yes i took there... It Is a protocol used for coffee machine keys..

**Comment by Sil333033** [comment]
May i see it in action?

**Comment by Willy-JL** [comment]
Still would like to see it in action, but ill merge in the meantime. Ill talk to you on discord.

Thanks! :D

**Comment by haisenteck** [comment]
> Still would like to see it in action, but ill merge in the meantime. Ill talk to you on discord.
> 
> Thanks! :D
yes, see attachment photo for a read.
IMG_20231201_124047
IMG_20231201_124036
IMG_20231201_124026

**Pull request merged**
