### PR TITLE
Add Saflok and MyKey KDFs

### PR DESCRIPTION
**Pull request by noproto**
# What's new

- Added new KDF plugins for the NFC app

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by Willy-JL** [comment]
thanks!

we got another PR for mykey recently in #467, should i revert that in favor of this one? im not really sure about the difference...

**Comment by Willy-JL** [comment]
fro ma cursory look this implementation seems more in line with the intended use of supported_cards plugins, expanding on the base protocols already implemented, while the on in #467 looks more like a separate protocol?

**Comment by noproto** [comment]
Yeah, one is a plugin and the other is modifying the protocol itself. Almost seems like the other PR is assuming every ST25TB is MyKey.

**Comment by Willy-JL** [comment]
you're right, i hadn't noticed that...

**Comment by augustozanellato** [comment]
> Almost seems like the other PR is assuming every ST25TB is MyKey.

This PR also does that :)
If you look at the parse function you’ll see that it always returns true. 
My take on that parser (OFW PR#3262) tries to determine if the tag is actually a mykey or not, maybe it could still have some false positives, but imho it’s better than blindly parsing everything.

**Pull request merged**
