### PR TITLE
Update Mayhem apps

### PR DESCRIPTION
**Pull request by eried**
Source: https://github.com/eried/flipperzero-mayhem/tree/next/flipper_companion_apps/applications/external

# What's new
Updated:
- morseflasher
- motion_detection
- nannycam
- qrcode
- camera
- marauder_companion

Removed:
- evilportal (since is included in marauder)

-----
# For the reviewer

- [x] I've uploaded the firmware with this patch to a device and verified its functionality
- [x] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by Willy-JL** [comment]
overwriting the folders like this discards all the edits that we made to optimize the apps for xtreme... i will close and update them myself then link here. thanks anyway

**Comment by Willy-JL** [comment]
for a concrete idea, this includes support for system keyboard with extra symbols and streamlined interface, support for `input keyboard` cli command in on-screen keyboard, support for asset pack icons in app (plus reduced fap size for faster loading because of it)

updated via 0d2f0fce3696629c8a67e6484c9bf38630a96c85

**Comment by eried** [comment]
Oh, thanks! I was not aware of the improvements, thats why I though it was some weird previous versions while updating the apps (based on the other files). Do you have some automated updater to inject those changes?

**Comment by Willy-JL** [comment]
not yet, done by hand for now

**Pull request closed without merging**
