### PR TITLE
Remove tiddies from Flipper CLI

### PR DESCRIPTION
**Pull request by FeyXieXzf**
# What's new

- As the title says

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- *citation: the is just a small rollback change so uploading the fw to check is unnecessary*
- [x] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
🤡

**Comment by FeyXieXzf** [comment]
> * Dont see why
Because IMO not everyone wants to see your "artworks" everywhere.
> * What makes you think you are "THE REVIEWER"? Is english really that hard?
Sorry. I'm not a native English speaker.

**Comment by ClaraCrazy** [comment]
Guess what, my firmware my style. Dont wanna see it? Dont look at it

**Comment by akopachov** [comment]
> > * Dont see why
> 
> Because IMO not everyone wants to see your "artworks" everywhere.
> 
> > * What makes you think you are "THE REVIEWER"? Is english really that hard?
> 
> Sorry. I'm not a native English speaker.

Just fork it, make a build for yourself and have your own build with whatever artwork you want.

**Comment by akopachov** [comment]
Here are few suggestions for your own forked FW name:

- Boring-Xtreme
- Amish-Xtreme
- Safe-Xtreme

**Comment by ClaraCrazy** [comment]
lmao. 

How about un-xtreme

**Comment by FlipperKev** [comment]
Yall petty af

**Comment by ClaraCrazy** [comment]
ongfrfrnocap

**Comment by Willy-JL** [comment]
L

**Comment by N-coder82** [comment]
I'm watching the repo, love the firmware, and this is **really** funny, as for my comment on this same as what Alex said, just fork it and call it anti-xtreme

**Comment by akopachov** [comment]
Oh, here is one more good name - Xtremeless

**Comment by FlipperKev** [comment]
😒

**Comment by FeyXieXzf** [comment]
I'd personally recommend you revise your wiki in order to remove inaccurate information.

**Comment by xAstroBoy** [comment]
> I'd personally recommend you revise your wiki in order to remove inaccurate information.

i personally suggest to mind your own dang firmware code, is xtreme style, let it be.

**Pull request closed without merging**
