### PR TITLE
SubGHZ Repeater, Enable Sound Saved to Last Settings.

### PR DESCRIPTION
**Pull request by LeeroysHub**
# What's new

SubGHZ Repeater.  Re-transmit keys with no user interaction.

-----
# For the reviewer

- [Y] I've uploaded the firmware with this patch to a device and verified its functionality
- [Y] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by subeax** [comment]
@LeeroysHub 
"config -> Lock Keyboard" does not work:)

**Comment by LeeroysHub** [comment]
Thankyou!

**Comment by Willy-JL** [comment]
very well done!

i just fixed up a few bits of logic with the timer being allocated even if it already existed, changed it to a type once instead of timer periodic and stopping on first callback. also made it so variable items can be set as locked without passing the text again, fixes duplication. also the binraw index is already done with the enum, no need to keep a separate index :D. and the binraw/repeater logic could have been a bit cleaner in receiver enter, but the idea was absolutely correct.

i think i will do one last change, so that when i nrepeater mode the receiver view doesnt show received signals. its a bit confusing when you have signals, then switch to repeater and the signals are still there... no indication of repeater apart from led/sound, and you wont get new signals in the list.

other than that all looks great, thanks!

**Comment by Willy-JL** [comment]
changed it instead so that when enabling repeater it will check if history has signals and ask to discard or keep them

**Comment by LeeroysHub** [comment]
I have just changed the Repeater code to properly get the Key transmit Time. Te * Bits is the time for s key to transmit, not Te in Milliseconds. Small change, but want to make it all correct!

**Pull request merged**
