### PR TITLE
SubGhz protocol integrations (Weather, Pocsag, TPMS)

### PR DESCRIPTION
**Pull request by htotoo**
# What's new

- Added the weather station the Weather, TPMS, Pocsag protocols.
- Added an option to Ignore Weather and Ignore TPMS packets.
- Can save / Load sub files for the protocols above.
- Can send Nexus-TH and Acurite_592TXR weather data.
- Since the operation fully included, removed the Pocsag app, and removed the Weather station app. (Kept TPMS, since there is a resync command)

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Review by Brandylee24 — CHANGES_REQUESTED** [review]
2021-10-26_UPS_Releases_3Q_2021_2058.pdf

**Comment by htotoo** [comment]
Just spam, (s)he spams all around github..

**Comment by Willy-JL** [comment]
Looks great, thank you so much!

**Comment by V1223** [comment]
could someone please advise me what setting to run when using sub ghz to capture weather station and pager. specifically the modulation any knowledge is greatly appreciated. me and wife are just begging our coding and pentesting learning. but we live in rural vietnam and dont always have access to internet so its slow going.

**Comment by Willy-JL** [comment]
> could someone please advise me what setting to run when using sub ghz to capture weather station and pager. specifically the modulation any knowledge is greatly appreciated. me and wife are just begging our coding and pentesting learning. but we live in rural vietnam and dont always have access to internet so its slow going.

in europe atleast it is usually am650 433.92mhz for weather station, not sure elsewhere

**Comment by varenc** [comment]
> could someone please advise me what setting to run when using sub ghz to capture weather station and pager. specifically the modulation any knowledge is greatly appreciated. me and wife are just begging our coding and pentesting learning. but we live in rural vietnam and dont always have access to internet so its slow going.

I'd like to echo this sentiment. With the removal of the Weather Station app it's now much harder for a novice to discover the weather station functionality.  The main value of the old Weather Station app is that its presence advertised the ability and it defaulted to a reasonable frequency and modulation for weather.  A brand new Flipper user will have a much harder time discovering this ability exists, which is a shame since it's a very cool out of the box thing.  

Not sure what a solution would look like but wanted to mention this anyway.  433.92MHz / AM650 aren't that hard to remember for those that care but the I think the bigger lose is discoverability.

**Comment by Sil333033** [comment]
There is no "default". it could be 315mhz, it could be 433mhz, it could be 868mhz, it could be 915mhz or whatever frequency the weather station broadcasts at. It all depends on your region, but weather stations around you can also broadcast on frequencies that are "not allowed". Get an SDR and analyze the whole spectrum where its busy.

And for modulation, it could be anything too! So just play around and don't be scared to try things

**Comment by Willy-JL** [comment]
For added context, I have a weather station near my house, picks up just fine on the default of 433.92 AM650 (default as per "Reaet to default"
At the bottom), it's a Nexus-TH if I recall correctly. But I have seen some that only work on FM modulation. And frequency usually depends on location (433 is standard usually in EU, 315 is standard usually in US, this is regardless of weather station, it's same for remotes and similar).

**Pull request merged**
