### PR TITLE
Re-added the Roku infrared map and ir file

### PR DESCRIPTION
**Pull request by mahtjarohst**
# What's new

Just re-added the Roku ir_remote assets.

-----
# For the reviewer

The Roku remote for the ir_remote application was removed in one of the latest dev builds, so I just added it back as I use it a lot.

### CODE REVIEW

**Comment by ClaraCrazy** [comment]
We provide firmware, not files

**Comment by mahtjarohst** [comment]
Okay I understand. That being said, why is the samsung one still present in there? If that is the case, then shouldn't that also be removed?

**Comment by mahtjarohst** [comment]
Screenshot from 2023-11-15 09-21-31
Screenshot from 2023-11-15 09-22-04

I understand the need for cleaning up the example resources.

If that is the case, then these also ought to be removed. If I am misunderstanding the reason for these still being present, please let me know :)

**Comment by Willy-JL** [comment]
Those are the fucking examples we are talking about

**Comment by Willy-JL** [comment]
A simple example file of each type. And I'd argue that Samsung is gonna be more popular than roku. Download the old files and add them if you need them.

**Comment by mahtjarohst** [comment]
Thanks, I was only trying to help, as I noticed a functionality that I use was missing. I'm loving the hospitality so far.

On that note, I'd argue that the Roku is more popular, given how inexpensive they tend to be. Having both by default would be a huge plus, since they are both incredibly popular.

You're right though, it's not hard to just add the files myself, so that's what I'll do.

**Pull request closed without merging**
