### PR TITLE
Updated Radar Scanner, BarcodeGen, New Terminal Menu

### PR DESCRIPTION
**Pull request by MatthewKuKanich**
# What's new

- Reworked the interface to be easier to use/see
- Modified the logic to accept input from pin 2 and set an alternate ground to pin 3
- This allows for anyone to use the app with just the radar unit, no need to build a module
- Alternate pinout is toggle-able via right button press

- Added auto 5v on launch feature, thanks willy! :)
- Reworked a couple functions to be cleaner

-----
# For the reviewer

- [ ] I've uploaded the firmware with this patch to a device and verified its functionality
- [ ] I've confirmed the bug to be fixed / feature to be stable

### CODE REVIEW

**Comment by Willy-JL** [comment]
that 5v power attempt snippet actually is by @xMasterX :D

also we are moving all apps to Flipper-XFW/Xtreme-Apps, hadn't gotten to this app yet so its fine that you PR'd this here :)

**Review by Willy-JL — APPROVED** [review]
LGTM!

**Comment by MatthewKuKanich** [comment]
> that 5v power attempt snippet actually is by @xMasterX :D
> 
> also we are moving all apps to Flipper-XFW/Xtreme-Apps, hadn't gotten to this app yet so its fine that you PR'd this here :)

Gotcha, thanks for letting me know! I was told it was you, so wanted to make sure I gave credit. I'll do future app PRs there when the transition is ready. You should give the app a try now that it's more accessible! $5-10 for a 5 pack of radar units

**Comment by Willy-JL** [comment]
nice! also hopefully wont need to send update PRs, the point of the new repo is automated updates right from the original repository with `git bulk-update-apps`, our own secret sauce

**Comment by Willy-JL** [comment]
pulled the barcode changes from upstream in the apps repo, thanks for backporting for now tho.

menu input code looks fine, but forgot about updating vertical_offset. since this has same input as list and other similar menus, ill move it there and reuse that code. also simplified the drawing code a little.

am yet to flash, will do when im back home. looks fine tho!

**Pull request merged**
