### PR TITLE
V52 Release

### PR DESCRIPTION
**Pull request by Willy-JL**
### Added:
- New Apps:
  - BLE Spam (by @Willy-JL and @ECTO-1A @Spooks4576 @xAstroBoy @Mr-Proxy-source)
  - [ESP32GPS] Wardriver (by @Sil333033)
  - [J305] Atomic Dice Roller (by @nmrr)
  - [RCWL0516] Radar Scan (#381 by @MatthewKuKanich)
  - [YRM100] UHF RFID (by @frux-c)
- Apps: New app system, easier to maintain and update (#466 by @Willy-JL)
- BadKB: Ask to migrate badusb folder, show script elapsed time #335 (by @Willy-JL)
- BT: New `furi_hal_bt_custom_adv_*()` API for arbitrary ADV packets (by @Willy-JL)
- GUI:
  - New firmware updated splashscreen (by @ClaraCrazy)
  - New flashing firmware interface (by @Willy-JL)
  - Compact and Terminal main menu styles (#415 #388 by @MatthewKuKanich @Willy-JL)
  - Show errors on animation load, credits moved to Default Asset Pack (by @Willy-JL)
  - New Xtreme Lockscreen Setting to disable poweroff keybind (by @Willy-JL)
  - New `variable_item_list_get()` API for dynamic list items (by @Willy-JL)
  - OFW: Added 2 new dolphin animations
- Infrared: Remember GPIO settings (by @Sil333033)
- NFC:
  - Add Saflok and MyKey KDFs (#476 by @noproto)
  - New Mifare Classic keys (by @Stepzor11 #477 #449 by @z3r0l1nk)
  - Philips Sonicare read support (by @Sil333033)
  - UL: Transport card parsers Umarsh, Kazan, Moscow, Metromoney (by @assasinfil @Leptopt1los)
  - OFW: NTAG21X write, Mifare Classic nested auth, FeliCa UID emulation
- SubGhz:
  - Integrated Weather station, Pocsag and TPMS protocols (#438 #399 by @htotoo)
  - New Honeywell Security protocol (#434 by @htotoo)
  - Add X10 protocol (#472 by @jamisonderek)
  - New GPS Subdriving support to save signal coordinates (by @Sil333033)
  - UL: Support FAAC SLH Prog mode (by @xMasterX @Eng1n33r @Skorpionm)
  - UL: Save all settings, option to reset config to default (by @derskythe)
  - UL: More add manually and ignore options, 303.9mhz in default list (by @xMasterX)
  - OFW: Added Mastercode protocol

### Updated:
- Updated Apps:
  - Some apps close on short back press (by @Sil333033)
  - Tweaked some app names to fit the screen (by @Willy-JL)
  - [ESP32] Evil Portal: Support Marauder bins (by @Willy-JL Marauder PR by @0xchocolate)
  - [ESP32] WiFi Marauder: Save PCAPS to Flipper SD for WROOM boards (by @Willy-JL)
  - [ESP] Flasher: Support Multi-Fucc/Xeon (by @Sil333033), Turbo flash speed (by @0xchocolate)
  - [NMEA] GPS: Deepsleep mode (by @Sil333033)
  - Barcode: Brightness control (#415 by @MatthewKuKanich)
  - BT/USB Remote: Mouse acceleration (#428 by @LeeroysHub @Willy-JL), new Movie and PTT modes (by @hryamzik)
  - Mifare Fuzzer: Fixed for new NFC Stack (by @Sil333033)
  - RFID Fuzzer: Add Pyramid, Keri, Jablotron, Paradox, Indala26, Viking, IoProxXSF (#441 #440 #437 by @SkeletonMan03)
  - SubGhz Remote: New design (by @Svaarich @gid9798)
- Asset Packs: Refactored FBT integration for new resource system (by @Willy-JL)
- Desktop: Poweroff screen has button for battery info (#428 by @LeeroysHub @Willy-JL)
- Furi: Revamped `furi_check()` crashes show code file paths (by @Willy-JL)
- FBT/CLI: Enable backlight when opening apps (by @ClaraCrazy)
- GPIO: Display 5v locked if charging (by @Sil333033)
- GUI: Setting for time/random file naming (by OFW), include protocol name prefix (by @Willy-JL)
- Infrared: New universal remote design (by OFW), ported to customs (by @xMasterX @Svaarich) and extras (by @Willy-JL)
- Keyboard: Press Ok in cursor mode to toggle select all text (by @Willy-JL)
- Loader: More user friendly API Mismatch error (by @Willy-JL)
- RGB Backlight: Add Off color preset, change LEDs naming to 1,2,3 (by @Willy-JL)
- RPC: Don't enable backlight for app/qflipper inputs (by @ClaraCrazy)
- Resources: Refactored app resources, cleaned up included files, new Tesla files, fixed iOS BadKB demo (by @Willy-JL)
- UL: Infrared: Updated universal remote assets (by @amec0e)
- OFW: Refactors: NFC stack, FreeRTOS imports, resource collection, hw targets, mbedtls crypto (porting efforts by @xMasterX @Willy-JL @Sil333033)

### Fixed:
- Apps: SubGhz Playlist: No out of memory when playing large playlists #425 (by @Willy-JL)
- Desktop: Only 1 valid animation won't show fallback (#455 by @perryrh0dan @Willy-JL)
- Storage: Improved rename/copy checks (by OFW), safer and compatible rename/move API (by @Willy-JL)
- SubGhz: New ignore flag system binary compatible with OFW apps, old method was saturated (by @Willy-JL)
- Xtreme Settings: Reset Menu option properly allows cancelling (by @Willy-JL)
- OFW: BT, Furi, GUI, iButton, RFID, Storage, SubGhz: General fixes and improvements
- OFW: Furi: Fix HardFault crashes for deep sleep with Bluetooth

### Removed:
- Removed Apps:
  - POCSAG Pager: Integrated into SubGhz
  - Weather Station: Integrated into SubGhz
  - [ESP32GPS] WiFi Sniff: Replaced by [ESP32GPS] Wardriver
  - [MAYHEM] Evil Portal: Integrated into [MAYHEM] Marauder
- [ESP] Flasher: Evil Portal bins gone, superseded by Marauder bins

### Known Issues:
- NFC: Refactored stack regressions:
  - Apps: Mifare Nested: Broken and removed, will be replaced soon
  - Apps: ESubGhz Chat: Encryption key sharing via NFC broken and removed, fate unknown
  - NFC: EMV (credit/debit card) support broken and removed, will be remade eventually
  - NFC: Possible read/emulate glitches with Mifare Classic, Mifare Mini and NFC-V
  - NFC: Mifare Classic add manually with custom UID temporarily removed
  - NFC: Some extra actions missing (eg. Unlock SLIX-L)
  - CLI: NFC CLI interface temporarily removed

### CODE REVIEW

**Comment by N-coder82** [comment]
Yayayayyayayayayayyayay!!!!

**Review by Sil333033 — APPROVED** [review]
wen rilise

**Comment by Willy-JL** [comment]
cwawa wen rilis?

**Review by ClaraCrazy — APPROVED** [review]

**Comment by ClaraCrazy** [comment]
weweawe now

**Pull request merged**
